import React from 'react';
import {AbsoluteFill,Audio,interpolate,spring,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';
import {scenes} from './sceneData';
import {colors} from './styles';
const Grid=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{overflow:'hidden',opacity:.28}}><div style={{position:'absolute',inset:-200,backgroundImage:`linear-gradient(rgba(139,92,246,.18) 1px,transparent 1px),linear-gradient(90deg,rgba(139,92,246,.18) 1px,transparent 1px)`,backgroundSize:'80px 80px',transform:`perspective(700px) rotateX(62deg) translateY(${(f*1.5)%80}px) scale(1.4)`}}/></AbsoluteFill>};
const Particles=()=>{const f=useCurrentFrame();return <AbsoluteFill>{Array.from({length:34}).map((_,i)=>{const x=(i*71)%100,y=(i*37)%100,d=Math.sin(f/35+i)*22,s=2+(i%3);return <div key={i} style={{position:'absolute',left:`${x}%`,top:`${y}%`,width:s,height:s,borderRadius:'50%',background:i%2?colors.violet:colors.violet2,opacity:.18+(i%5)*.08,transform:`translate(${d}px,${Math.cos(f/45+i)*14}px)`}}/>})}</AbsoluteFill>};
const Core=({scale=1}:{scale?:number})=>{const f=useCurrentFrame(),p=1+Math.sin(f/10)*.035;return <div style={{width:230*scale,height:230*scale,borderRadius:'50%',display:'flex',alignItems:'center',justifyContent:'center',transform:`scale(${p})`,background:'radial-gradient(circle,rgba(192,132,252,.95),rgba(139,92,246,.28) 38%,rgba(5,3,10,0) 72%)',boxShadow:'0 0 80px rgba(139,92,246,.55)'}}><div style={{width:108*scale,height:108*scale,borderRadius:'50%',border:`${3*scale}px solid ${colors.violet2}`,boxShadow:'inset 0 0 30px rgba(192,132,252,.45),0 0 35px rgba(139,92,246,.65)',transform:`rotate(${f*1.2}deg)`}}/></div>};
const Panel=({children,x=0,y=0,w=760,h=330}:{children:React.ReactNode;x?:number;y?:number;w?:number;h?:number})=><div style={{position:'absolute',left:x,top:y,width:w,minHeight:h,padding:34,boxSizing:'border-box',borderRadius:24,background:'linear-gradient(145deg,rgba(20,12,32,.96),rgba(8,5,13,.94))',border:`1px solid ${colors.line}`,boxShadow:'0 24px 90px rgba(0,0,0,.42),inset 0 0 45px rgba(139,92,246,.05)'}}>{children}</div>;
const Label=({children}:{children:React.ReactNode})=><div style={{fontSize:18,letterSpacing:3,color:colors.violet2,fontWeight:700}}>{children}</div>;
const Title=({title}:{title:string})=>{const f=useCurrentFrame(),{fps}=useVideoConfig(),p=spring({frame:f,fps,config:{damping:16,stiffness:100}});return <div style={{position:'absolute',left:90,top:72,transform:`translateY(${interpolate(p,[0,1],[30,0])}px)`,opacity:p}}><div style={{fontSize:42,fontWeight:800,color:colors.white}}>{title}</div><div style={{marginTop:12,width:90,height:4,background:colors.violet,borderRadius:4}}/></div>};
const Formula=()=>{const f=useCurrentFrame(),items=['ROLE','TASK','CONTEXT','DESIRED RESULT'];return <div style={{display:'flex',gap:18,alignItems:'center',justifyContent:'center'}}>{items.map((it,i)=><React.Fragment key={it}><div style={{padding:'24px 28px',borderRadius:18,border:`1px solid ${colors.violet}`,background:'rgba(139,92,246,.10)',color:colors.white,fontWeight:800,fontSize:22,transform:`translateY(${Math.sin(f/12+i)*5}px)`,boxShadow:'0 0 35px rgba(139,92,246,.16)'}}>{it}</div>{i<3&&<div style={{fontSize:30,color:colors.violet2}}>+</div>}</React.Fragment>)}</div>};
export const FirstStepLearner:React.FC=()=>{const f=useCurrentFrame(),{fps}=useVideoConfig(),sec=f/fps,scene=scenes.find(s=>sec>=s.start&&sec<s.end)??scenes[scenes.length-1];return <AbsoluteFill style={{background:colors.bg,color:colors.white,fontFamily:'Arial,Helvetica,sans-serif',overflow:'hidden'}}><Grid/><Particles/>
{scene.id==='SCENE_1'&&<><Title title={scene.title}/><div style={{position:'absolute',left:240,top:300}}><Core scale={.9}/></div><div style={{position:'absolute',right:240,top:300}}><Core scale={.9}/></div><Panel x={100} y={650} w={760} h={170}><Label>OUTPUT A</Label><div style={{fontSize:30,marginTop:20,color:colors.muted}}>Generic • Average • Unfocused</div></Panel><Panel x={1060} y={650} w={760} h={170}><Label>OUTPUT B</Label><div style={{fontSize:30,marginTop:20}}>Specific • Clear • Useful</div></Panel><div style={{position:'absolute',left:0,right:0,top:930,textAlign:'center',fontSize:28,color:colors.violet2}}>{scene.text}</div></>}
{scene.id==='SCENE_2'&&<><Title title={scene.title}/><div style={{position:'absolute',left:700,top:270}}><Core scale={1.1}/></div><Panel x={230} y={620} w={1460} h={180}><div style={{fontSize:38,textAlign:'center',fontWeight:700}}>{scene.text}</div><div style={{fontSize:23,textAlign:'center',marginTop:18,color:colors.muted}}>Clear instructions give the system a clearer target.</div></Panel></>}
{scene.id==='SCENE_3'&&<><Title title={scene.title}/><Panel x={230} y={240} w={1460} h={600}><Label>HOLOGRAPHIC CHAT</Label><div style={{marginTop:40,padding:26,borderRadius:16,background:'rgba(139,92,246,.08)',fontSize:34}}>{scene.text}</div><div style={{marginTop:42,fontSize:24,color:colors.muted}}>AI RESPONSE</div><div style={{marginTop:18,fontSize:32,lineHeight:1.35}}>“Try our delicious new chai… a perfect cup for every moment.”</div></Panel></>}
{scene.id==='SCENE_4'&&<><Title title={scene.title}/><div style={{position:'absolute',left:120,top:250,right:120,display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}>{[['ROLE','Creative social media copywriter'],['TASK','Write an Instagram caption'],['CONTEXT','Handmade masala chai • audience 20–35'],['DESIRED RESULT','Catchy • 1 emoji • short CTA']].map(([a,b])=><Panel key={a} x={0} y={0} w={800} h={230}><Label>{a}</Label><div style={{fontSize:27,marginTop:22,lineHeight:1.3}}>{b}</div></Panel>)}</div><div style={{position:'absolute',left:0,right:0,bottom:70,textAlign:'center'}}><Formula/></div></>}
{scene.id==='SCENE_5'&&<><Title title={scene.title}/><Panel x={90} y={260} w={820} h={560}><Label>WEAK PROMPT</Label><div style={{fontSize:30,marginTop:26,color:colors.muted}}>Generic result with little direction.</div><div style={{marginTop:60,fontSize:26}}>“Try our delicious new chai…”</div></Panel><Panel x={1010} y={260} w={820} h={560}><Label>STRUCTURED PROMPT</Label><div style={{fontSize:30,marginTop:26}}>Specific audience, context and desired outcome.</div><div style={{marginTop:60,fontSize:26}}>A focused launch caption with a clear CTA.</div></Panel><div style={{position:'absolute',bottom:80,left:0,right:0,textAlign:'center',fontSize:34,fontWeight:800}}>{scene.text}</div></>}
{scene.id==='SCENE_6'&&<><Title title={scene.title}/><div style={{position:'absolute',left:80,right:80,top:430}}><Formula/></div><div style={{position:'absolute',bottom:100,left:0,right:0,textAlign:'center',fontSize:28,color:colors.muted}}>Four simple pieces. One clearer instruction.</div></>}
{scene.id==='CTA'&&<div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{padding:'24px 52px',borderRadius:50,border:`2px solid ${colors.violet}`,background:'rgba(139,92,246,.12)',fontSize:34,fontWeight:800,boxShadow:'0 0 60px rgba(139,92,246,.3)'}}>{scene.text}</div></div>}
{scene.id==='SCENE_7'&&<><Title title={scene.title}/><Panel x={90} y={280} w={820} h={500}><Label>BEFORE</Label><div style={{fontSize:32,marginTop:30,color:colors.muted}}>&quot;ek email likho&quot;</div></Panel><Panel x={1010} y={280} w={820} h={500}><Label>AFTER</Label><div style={{fontSize:27,marginTop:30,lineHeight:1.45}}>ROLE: professional HR manager<br/>TASK: leave request email<br/>CONTEXT: 3 din ki leave<br/>RESULT: polite, formal, short</div></Panel><div style={{position:'absolute',bottom:100,left:0,right:0,textAlign:'center'}}><Formula/></div></>}
{scene.id==='SCENE_8'&&<><Title title={scene.title}/><div style={{position:'absolute',left:720,top:250}}><Core scale={1.15}/></div><div style={{position:'absolute',left:0,right:0,top:660,textAlign:'center',fontSize:32,fontWeight:700}}>{scene.text}</div><div style={{position:'absolute',left:0,right:0,top:730,textAlign:'center',fontSize:24,color:colors.muted}}>Important facts, numbers and claims should still be checked.</div></>}
{scene.id==='SCENE_9'&&<><Title title={scene.title}/><div style={{position:'absolute',left:0,right:0,top:350}}><Formula/></div><div style={{position:'absolute',left:0,right:0,top:520,textAlign:'center',fontSize:32}}>Take one old prompt. Rewrite it with the four blocks.</div><div style={{position:'absolute',left:0,right:0,bottom:110,textAlign:'center',fontSize:28,color:colors.violet2}}>ROLE → TASK → CONTEXT → DESIRED RESULT</div></>}
{scene.id==='SCENE_10'&&<><div style={{position:'absolute',left:0,right:0,top:170,textAlign:'center'}}><Core scale={1.35}/></div><div style={{position:'absolute',left:0,right:0,top:520,textAlign:'center',fontSize:58,fontWeight:900}}>FIRST STEP LEARNER</div><div style={{position:'absolute',left:0,right:0,top:620,textAlign:'center',fontSize:30,color:colors.violet2}}>LEARN AI • BUILD SKILLS • GROW YOUR FUTURE</div><div style={{position:'absolute',left:0,right:0,bottom:90,textAlign:'center',fontSize:27,color:colors.muted}}>Every journey starts with a first step.</div></>}
<Audio src={staticFile('audio/voiceover.mp3')} volume={1}/></AbsoluteFill>};
