import asyncio
from pathlib import Path
import edge_tts
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'public'/'audio'/'voiceover.mp3'
TEXT='''Assalamu Alaikum wa Rahmatullahi wa Barakatuh.\n\nAgar AI itna hi powerful hai... to ek hi AI se, do alag logon ko, bilkul alag result kyun milta hai? Kisi ko ek average sa jawaab milta hai... aur kisi ko bilkul professional output. AI same hai. Sawaal wahi hai. Fark kahaan hai?\n\nProblem AI mein nahi hai. Problem ye hai ki hum AI se baat karte waqt bahut kam batate hain. Hum sochte hain AI hamara mann padh lega. Lekin AI koi mind-reader nahi hai — wo sirf utna hi samajhta hai jitna hum usko batate hain.\n\nChaliye ise live dekhte hain. Maan lijiye humein ek Instagram caption chahiye apne naye chai brand ke launch ke liye. Ek beginner aksar AI ko sirf itna likhta hai — chai brand ke liye caption likho. Dekhte hain AI kya deta hai.\n\nAb wahi AI, wahi task — lekin is baar hum use puri jaankari dete hain. Role batate hain, task clearly define karte hain, context dete hain, aur exactly wo result maangte hain jo chahiye.\n\nAb dono results ko saath mein dekhiye. Ek taraf ek generic, bhula dene wali line hai. Doosri taraf ek caption hai jo specific hai, emotion create karti hai, aur clearly batati hai audience ko kya karna hai. Fark AI ka nahi — instruction ka hai.\n\nYaad rakhne ke liye ek simple formula hai: Role, plus Task, plus Context, plus Desired Result. Bas ye chaar cheezein AI ko batao, aur result completely badal jaata hai.\n\nAgar aap AI ko sirf istemaal nahi, balki sahi tareeke se kaam mein lena seekhna chahte hain, to First Step Learner ko Subscribe kar lijiye.\n\nAb aap khud try kar sakte hain. Chahe aap ChatGPT use karein, Gemini, ya koi bhi AI tool — agli baar jab prompt likhein, pehle apna purana style dekhiye, aur phir formula laga kar dobara likhiye.\n\nEk important baat — better prompt matlab perfect AI nahi. AI abhi bhi galtiyaan kar sakta hai. Isliye important facts, numbers ya jaankari hamesha ek baar khud check kar lijiye.\n\nAapka challenge ye hai — koi bhi ek kaam jo aap normally AI se karwate hain, use aaj formula laga kar dobara likhiye. Role, Task, Context, aur Desired Result add kijiye, aur dekhiye fark khud.\n\nAI ko use karna ek tool seekhna nahi hai. AI ke saath kaam karna ek skill hai. Yahaan First Step Learner par, hum yahi skill seekhte hain — practical, simple, aur step by step.\n\nJazakAllahu Khairan.\nAssalamu Alaikum wa Rahmatullahi wa Barakatuh.\nAllah Hafiz.'''
async def main():
    OUT.parent.mkdir(parents=True,exist_ok=True)
    await edge_tts.Communicate(TEXT,voice='hi-IN-MadhurNeural').save(str(OUT))
    print(f'Saved {OUT}')
if __name__=='__main__': asyncio.run(main())
