from pathlib import Path
import json
import shutil


ROOT = Path(__file__).resolve().parent.parent

GENERATED_DIR = ROOT / "generated"
PUBLIC_DIR = ROOT / "public"

PUBLIC_GENERATED_DIR = PUBLIC_DIR / "generated"
PUBLIC_AUDIO_DIR = PUBLIC_DIR / "audio"
PUBLIC_IMAGES_DIR = PUBLIC_DIR / "images"
PUBLIC_DOCUMENTS_DIR = PUBLIC_DIR / "documents"
PUBLIC_MAPS_DIR = PUBLIC_DIR / "maps"


def ensure_directories():
    directories = [
        PUBLIC_GENERATED_DIR,
        PUBLIC_AUDIO_DIR,
        PUBLIC_IMAGES_DIR,
        PUBLIC_DOCUMENTS_DIR,
        PUBLIC_MAPS_DIR,
    ]

    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)


def require_file(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"Required file missing: {path}")

    if path.is_file() and path.stat().st_size == 0:
        raise RuntimeError(f"Required file is empty: {path}")


def copy_if_exists(source: Path, destination: Path):
    if source.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        print(f"Copied: {source} -> {destination}")
        return True

    return False


def copy_generated_files():
    """
    Copy all runtime JSON files generated by the story pipeline
    into public/generated so Remotion can load them with staticFile().
    """

    required_files = [
        "story.json",
        "visual_plan.json",
        "subtitles.json",
        "assets.json",
    ]

    optional_files = [
        "map_data.json",
        "word_timings.json",
        "sources.json",
    ]

    print("=" * 60)
    print("COPYING GENERATED RUNTIME FILES")
    print("=" * 60)

    for filename in required_files:
        source = GENERATED_DIR / filename
        destination = PUBLIC_GENERATED_DIR / filename

        require_file(source)
        shutil.copy2(source, destination)

        print(f"✓ {filename}")

    for filename in optional_files:
        source = GENERATED_DIR / filename
        destination = PUBLIC_GENERATED_DIR / filename

        if source.exists():
            shutil.copy2(source, destination)
            print(f"✓ {filename}")
        else:
            print(f"- {filename} not present; skipping")


def copy_audio_files():
    """
    Verify the generated narration and existing background audio.
    Audio files already live inside public/audio and public/music,
    so we do not duplicate them.
    """

    narration = PUBLIC_AUDIO_DIR / "narration.mp3"
    music = PUBLIC_DIR / "music" / "investigation.mp3"
    ambience = PUBLIC_AUDIO_DIR / "ambience" / "atmosphere.mp3"

    require_file(narration)
    require_file(music)
    require_file(ambience)

    print("=" * 60)
    print("AUDIO ASSETS")
    print("=" * 60)

    print(f"✓ Narration: {narration}")
    print(f"✓ Music: {music}")
    print(f"✓ Ambience: {ambience}")


def copy_visual_assets():
    """
    Copy any generated/local visual assets if they exist.
    Missing optional directories are not treated as errors.
    """

    source_dirs = [
        (GENERATED_DIR / "images", PUBLIC_IMAGES_DIR),
        (GENERATED_DIR / "documents", PUBLIC_DOCUMENTS_DIR),
        (GENERATED_DIR / "maps", PUBLIC_MAPS_DIR),
    ]

    print("=" * 60)
    print("VISUAL ASSETS")
    print("=" * 60)

    for source_dir, destination_dir in source_dirs:
        if not source_dir.exists():
            print(f"- {source_dir.name}: no generated directory")
            continue

        destination_dir.mkdir(parents=True, exist_ok=True)

        copied = 0

        for source_file in source_dir.rglob("*"):
            if not source_file.is_file():
                continue

            relative_path = source_file.relative_to(source_dir)
            destination_file = destination_dir / relative_path

            destination_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_file, destination_file)

            copied += 1

        print(f"✓ {source_dir.name}: {copied} file(s)")


def build_asset_manifest():
    """
    Create the runtime asset manifest consumed by the documentary pipeline.
    """

    visual_plan_file = GENERATED_DIR / "visual_plan.json"

    visual_types = set()

    if visual_plan_file.exists():
        try:
            visual_plan = json.loads(
                visual_plan_file.read_text(encoding="utf-8")
            )

            for beat in visual_plan.get("beats", []):
                visual_type = beat.get("visual_type")

                if visual_type:
                    visual_types.add(str(visual_type))

        except Exception as exc:
            print(f"Warning: could not read visual plan: {exc}")

    manifest = {
        "version": 2,

        "runtime": {
            "narration": "audio/narration.mp3",
            "music": "music/investigation.mp3",
            "ambience": "audio/ambience/atmosphere.mp3",

            "generated": {
                "story": "generated/story.json",
                "visual_plan": "generated/visual_plan.json",
                "subtitles": "generated/subtitles.json",
                "assets": "generated/assets.json",
                "map_data": "generated/map_data.json",
            },
        },

        "audio": {
            "narration_volume": 1.0,
            "music_volume": 0.075,
            "ambience_volume": 0.035,
            "music_loop": True,
            "ambience_loop": True,
        },

        "visuals": {
            "automatic": True,
            "manual_visual_assets_required": False,
            "visual_types_detected": sorted(visual_types),
        },

        "maps": {
            "automatic": True,
            "geocoding": True,
            "route_animation": True,
            "fallback_enabled": True,
        },

        "audio_effects": {
            "manual_sfx_required": False,
        },
    }

    output_file = GENERATED_DIR / "assets.json"

    output_file.write_text(
        json.dumps(
            manifest,
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    # Also copy the freshly-created manifest into the Remotion runtime folder.
    PUBLIC_GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    shutil.copy2(
        output_file,
        PUBLIC_GENERATED_DIR / "assets.json",
    )

    print(f"✓ Asset manifest written: {output_file}")


def validate_runtime_files():
    """
    Final check before validate_pipeline.py runs.
    """

    print("=" * 60)
    print("VALIDATING PREPARED RUNTIME FILES")
    print("=" * 60)

    required_runtime_files = [
        PUBLIC_GENERATED_DIR / "story.json",
        PUBLIC_GENERATED_DIR / "visual_plan.json",
        PUBLIC_GENERATED_DIR / "subtitles.json",
        PUBLIC_GENERATED_DIR / "assets.json",
        PUBLIC_AUDIO_DIR / "narration.mp3",
        PUBLIC_DIR / "music" / "investigation.mp3",
        PUBLIC_AUDIO_DIR / "ambience" / "atmosphere.mp3",
    ]

    for path in required_runtime_files:
        require_file(path)
        print(f"✓ {path.relative_to(ROOT)}")

    map_data = PUBLIC_GENERATED_DIR / "map_data.json"

    if map_data.exists():
        require_file(map_data)
        print(f"✓ {map_data.relative_to(ROOT)}")
    else:
        print("⚠ map_data.json not found; map fallback will be used")


def main():
    print("=" * 60)
    print("FIRST STEP LEARNER - ASSET PREPARATION")
    print("=" * 60)

    ensure_directories()

    # Build manifest first so assets.json is always current.
    build_asset_manifest()

    # Copy all generated JSON files, including story.json.
    copy_generated_files()

    # Verify audio files.
    copy_audio_files()

    # Copy optional visual assets.
    copy_visual_assets()

    # Final runtime verification.
    validate_runtime_files()

    print("=" * 60)
    print("ASSETS PREPARED SUCCESSFULLY")
    print("=" * 60)

    print(f"Runtime directory: {PUBLIC_GENERATED_DIR}")
    print("Generated files are ready for Remotion.")


if __name__ == "__main__":
    main()
