import React from 'react';
import type {VisualBeat as Beat} from '../engineTypes';
import {CinematicText} from './CinematicText';
import {LocationCard} from './LocationCard';
import {TimelineAnimation} from './TimelineAnimation';
import {MapAnimation} from './MapAnimation';
import {PhotoPanel} from './PhotoPanel';
import {DocumentPanel} from './DocumentPanel';
import {NewspaperPanel} from './NewspaperPanel';
import {EvidencePanel} from './EvidencePanel';
import {QuoteCard} from './QuoteCard';
import {StatisticsPanel} from './StatisticsPanel';
export const VisualBeat:React.FC<{beat:Beat}>=({beat})=>{const d=beat.data??{};const s=beat.text;switch(beat.type){case 'map':{const c=d.coordinates as {from?:{lat:number;lon:number}|null;to?:{lat:number;lon:number}|null}|undefined;return <MapAnimation from={String(d.from??'')} to={String(d.to??'')} fromCoord={c?.from} toCoord={c?.to}/>;}case 'timeline':return <TimelineAnimation date={String(d.date??'')} event={String(d.event??s)}/>;case 'location':return <LocationCard location={String(d.location??'LOCATION')} text={s}/>;case 'photo':return <PhotoPanel src={beat.asset} title={String(d.location??'VISUAL')} text={s} reconstructed/>;case 'document':return <DocumentPanel src={beat.asset} text={s}/>;case 'newspaper':return <NewspaperPanel src={beat.asset} text={s}/>;case 'evidence':return <EvidencePanel items={Array.isArray(d.items)?d.items.map(String):[s]}/>;case 'quote':return <QuoteCard quote={String(d.quote??s)}/>;case 'statistic':return <StatisticsPanel value={String(d.value??'')} label={String(d.label??s)}/>;case 'unknown':return <EvidencePanel title='WHAT REMAINS UNKNOWN' items={Array.isArray(d.items)?d.items.map(String):[s]}/>;case 'ending':return <CinematicText eyebrow='DOCUMENTARY' title='REAL STORY. REAL QUESTIONS.' text={s}/>;case 'cold_open':return <CinematicText eyebrow='THE STORY' title='THIS REALLY HAPPENED' text={s}/>;default:return <CinematicText eyebrow='NARRATION' title={s}/>;}};
